spring:
  profiles:
    active: local
  rabbitmq:
    host: ${RABBIT_MQ_HOST:10.4.14.43}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:root}
    password: ${RABBIT_MQ_PASSWORD:hEB$%47kikVNa8S5}

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info