apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana-claim1
  name: nfs-client-root-pvc
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 99Gi
  selector:
    matchLabels:
      pv: pv-nfs-client-root
status: {}
