apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kibana
  labels:
    pv: pv-kibana
spec:
  mountOptions:
    - nolock
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server:  10.4.6.32  #这里请写nfs服务器的ip
    path: /var/services/homes/bigdata/k8s/kibana

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kibana-claim1
  name: kibana-claim1
  namespace: sc
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      pv: pv-kibana
status: {}
