---
#es master节点的持久卷
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-zipkin
  labels:
    pv: pv-zipkin
spec:
  mountOptions:
    - nolock
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  nfs:
    server:  10.4.6.32  #这里请写nfs服务器的ip 
    path: /var/services/homes/bigdata/k8s/zipkin
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zipkin-server-claim0
  name: zipkin-server-claim0
  namespace: sc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs
  selector:
    matchLabels:
      pv: pv-zipkin
status: {}
