spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:10.4.14.43}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:root}
    password: ${RABBIT_MQ_PASSWORD:hEB$%47kikVNa8S5}
  redis:
    host: ${REDIS_HOST:10.4.14.24}
    port: ${REDIS_PORT:6379}
    #password: ${REDIS_PASSWORD:jzt600998}
  #spring boot admin的登陆账号和密码配置
  security:
    user:
      name: admin
      password: 123456
  #通过rabbit MQ将日志发给zipkin
  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

management:
  endpoints:
    web:
      exposure:
        include: '*'
#日志相关配置
logging:
  level:
    org.springframework.security: DEBUG
  path: logs/
  file:
    max-size: 1GB


